### ISSUE TITLE
Could not open the project in VS2017

### ISSUE THREAD

**Issue by mrahman252003** [FabBag72/PD_TechTeam#1]
Hi,
The project I could not open, it shows the following dialog when trying to open
![Capture](https://user-images.githubusercontent.com/1430950/117550604-e5d56200-b049-11eb-85f9-8c02abf86d83.PNG)

**Comment by FabBag72** [comment]
Last month I have updated to 1.12.748.0. Could you try again?

**Comment by FabBag72** [comment]
Today I have updated to 1.12.752.0
